core-ftrace: add ; after RB_* macros
cppcheck throws an, put the ; back to clean this false positive.

core-ftrace.c:56:1: error: There is an unknown macro here somewhere.
Configuration is required. If RB_PROTOTYPE is a macro then please
configure it. [unknownMacro]
RB_PROTOTYPE(rb_tree, rb_node, rb, rb_node_cmp)

Signed-off-by: Colin Ian King <colin.king@canonical.com>