stress-lockbus: disable pcc builds, currently it breaks
CC=pcc PEDANTIC=1 make
CC stress-lockbus.c
stress-lockbus.c, line 386: compiler error: illegal address, op 23, node 0x55f9924104f0
error: /usr/bin/x86_64-linux-gnu-ccom terminated with status 1
make: *** [Makefile:800: stress-lockbus.o] Error 1

Signed-off-by: Colin Ian King <colin.i.king@gmail.com>