stress-epoll: only build EPOLLEXCLUSIVE if it is defined
Older kernels don't have EPOLLEXCLUSIVE to only test this if it
is defined.  Fixes build error:

stress-epoll.c:247:22: warning: declaration of ‘event’ shadows a previous local [-Wshadow]
   struct epoll_event event;
                      ^

stress-epoll.c:239:21: warning: shadowed declaration is here [-Wshadow]
  struct epoll_event event;
                     ^

stress-epoll.c: In function ‘test_epoll_exclusive’:
stress-epoll.c:376:17: error: ‘EPOLLEXCLUSIVE’ undeclared (first use in this function)
  event.events = EPOLLEXCLUSIVE;
                 ^

stress-epoll.c:376:17: note: each undeclared identifier is reported only once for each function it appears in

make[1]: *** [stress-epoll.o] Error 1

Signed-off-by: Colin Ian King <colin.king@canonical.com>