stress-vm-rw: fix build failure on ia64 with missing HAVE_CLONE
Fix yet another ia64 build failure.

stress-vm-rw.c: In function 'stress_vm_child':
stress-vm-rw.c:69:8: error: unknown type name 'context_t'
  const context_t *ctxt = (context_t *)arg;
        ^~~~~~~~~
stress-vm-rw.c:69:27: error: 'context_t' undeclared (first use in this
function); did you mean 'ucontext_t'?
  const context_t *ctxt = (context_t *)arg;
                           ^~~~~~~~~
                           ucontext_t

Signed-off-by: Colin Ian King <colin.king@canonical.com>