stress-netlink-proc: fix build with kernel v3.9
The PROC_EVENT_COREDUMP has been introduced in kernel version 3.10.
Don't use it with 3.9 headers.

Fixes build failure:

stress-netlink-proc.c: In function 'monitor':
stress-netlink-proc.c:108:8: error: 'PROC_EVENT_COREDUMP' undeclared (first use in this function)
   case PROC_EVENT_COREDUMP:
        ^

Signed-off-by: Baruch Siach <baruch@tkos.co.il>
Signed-off-by: Colin Ian King <colin.king@canonical.com>