stress-context: rename uc_link to uctx_link
Have to rename this to fix build issue on ia64:

CC stress-context.c
In file included from /usr/include/signal.h:306:0,
                 from stress-ng.h:91,
                 from stress-context.c:25:
stress-context.c:65:14: error: expected ';', ',' or ')' before '.' token
  ucontext_t *uc_link,

This occurs because of the following linux #define in ucontext.h:

arch/ia64/include/uapi/asm/ucontext.h

Tad annoying IMHO.

Signed-off-by: Colin Ian King <colin.king@canonical.com>