stress-userfault: add missing check for HAVE_CLONE
Fixes ia64 build failure:

stress-userfaultfd.c: In function 'stress_userfaultfd_child':
stress-userfaultfd.c:74:2: error: unknown type name 'context_t'; did you mean 'ucontext_t'?
  context_t *c = (context_t *)arg;
  ^~~~~~~~~

..etc

Signed-off-by: Colin Ian King <colin.king@canonical.com>