core-sched.c: fix uclibc-ng build
Since version 0.17.02 and commit
e75ecbc8994e94b9e151b1191c1888bd2821fe72, sched.h is not included before
including core-shim.h. The issue is that core-shim.h defines its own
sched_priority parameter in shim_sched_attr. When sched.h is included
after core-shim.h, the build will fail because __sched_priority will not
be found:

In file included from core-sched.c:25:
core-sched.c: In function 'stress_set_sched':
core-sched.c:170:22: error: 'struct shim_sched_attr' has no member named '__sched_priority'; did you mean 'sched_priority'?
  170 |                 attr.sched_priority = (unsigned int)sched_priority;
      |                      ^~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/d7d38dbb10f7f188da8dccc44a84a3c46a720bed

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>