stress-sock: fix build failure on some 32 bit arches
On some 32 bit arches on some kernels/libc flavours
struct __kernel_old_timeval is not defined and causes
the SIOCGSTAMP ioctl to break the build. So only build
it for 64 bit arches as a workaround.

Fixes:
stress-sock.c:189:19: error: invalid application of 'sizeof' to
incomplete type 'struct __kernel_old_timeval'
  189 |   ret = ioctl(fd, SIOCGSTAMP, &tv);

Signed-off-by: Colin Ian King <colin.king@canonical.com>