stress-msg: allocate msgq_ids on the heap, don't use the stack
clang-9 on RISC-V breaks when using dynamically allocated
msgq_ids array on the stack. Use the heap instead. Fixes
build issue:

fatal error: error in backend: RISC-V backend can't currently handle
functions that need stack realignment and have variable sized objects
clang: error: clang frontend command failed with exit code 70
(use -v to see invocation)
clang version 9.0.1-16
Target: riscv64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Signed-off-by: Colin Ian King <colin.king@canonical.com>