stress-regs: fix compilation error with gcc-8 on armel and ppc
Fix the following by putting void expressions in parenthesis. Seems like
a weird gcc issue where (void)v << 1 causes the failure:

stress-regs.c: In function 'stress_regs_helper':
stress-regs.c:945:5: error: void value not ignored as it ought to be
  stash64 = r1 + r2 + r3 + r4 + r5 + r6 + r7 + r8;
     ^~~~~~~

..but it appears as the following due to macro expansion obfuscation:

CC stress-regs.c
stress-regs.c: In function 'stress_regs_helper':
stress-regs.c:120:2: error: void value not ignored as it ought to be
  (void)expected;      \
  ^
stress-regs.c:132:3: note: in expansion of macro 'regs_check128'
   regs_check128(args, reg, expected, value); \
   ^~~~~~~~~~~~~
stress-regs.c:936:2: note: in expansion of macro 'REGS_CHECK'
  REGS_CHECK(args, "r1", v << 1, r1);

Signed-off-by: Colin Ian King <colin.i.king@gmail.com>