Makefile: fix build with kernel < 5.6
Fix the following build failure with kernel >= 5.1 and < 5.5 (i.e.
before
https://github.com/torvalds/linux/commit/9e3aa61ae3e01ce1ce6361a41ef725e1f4d1d2bf)
raised since version 0.11.21 and
https://github.com/ColinIanKing/stress-ng/commit/3d6fccdbe53d0cbcb75dd4b91571aaaae7ee1ad4:

In file included from stress-io-uring.c:26:
io-uring.h:1:9: error: macro names must be identifiers
    1 | #define #define HAVE_IORING_OP_NOP 0
      |         ^

Moreover, IORING_OP_FALLOCATE is not available before kernel 5.6 and
https://github.com/torvalds/linux/commit/d63d1b5edb7b832210bfde587ba9e7549fa064eb

Fixes:
 - http://autobuild.buildroot.org/results/1bf3f2bbc849bdce531d56b1024fa87f0c1ae667

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>