stress-sysfs: rename os_release to linux_release
os_release causes tcc to break with:

stress-sysfs.c:718: error: bad terminal (1)
error: /usr/bin/x86_64-linux-gnu-pcc-cpp terminated with status 1

Renaming os_release fixes this.

Signed-off-by: Colin Ian King <colin.i.king@gmail.com>