stress-cache: check RISCV_HWPROBE_EXT_ZICBOZ support for stress_cache_bzero
RISCV_HWPROBE_EXT_ZICBOZ flag from kernel headers on RISC-V was only
added in 6.7, test build will fail with an older kernel with:
    error: ‘RISCV_HWPROBE_EXT_ZICBOZ’ undeclared

Check the flag first to fix this issue.

Fixes: f8654a05f4 ("stress-cache: add stress_cache_bzero() to support cache-based bzero")
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>