core-config-check: avoid gcc breakage when using -march=znver3 -O3 -funroll-loops
gcc 14 using -march=znver3 -O3 -funroll-loops breaks with:

core-asm-x86.h: Assembler messages:
core-asm-x86.h:382: Error: can't encode register '%ah' in an instruction requiring REX/REX2 prefix

Seems that gcc-15 is okay with this. Workaround this by disabling -O3 on
the caller of the inline function stress_cpu_x86_has_lahf_lm

Workaround: https://bugs.gentoo.org/show_bug.cgi?id=962017
Closes: https://github.com/ColinIanKing/stress-ng/issues/589

Signed-off-by: Colin Ian King <colin.i.king@gmail.com>